spring.application.name=task_management_app
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jooq.sql-dialect=MYSQL
spring.liquibase.drop-first=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.expiration=300000
jwt.secret=t12a12s12k12_12m12a12n12a12g12e12m12e12n12t12_12a21p12p
