spring.application.name=task_management_app
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jooq.sql-dialect=MYSQL
spring.liquibase.drop-first=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

dropbox.accessToken=${DROPBOX_ACCESS_TOKEN}
